In [45]:
import pandas as pd

In [46]:
df1 = pd.read_excel("data/new_dataset_mt_lxx_data.xlsx").fillna("")

In [47]:
df2 = pd.read_csv("data/exodus_bo_dss.csv").fillna("")

In [48]:
df2 = df2[df2.comments != "reconstructed"].copy().reset_index()

In [49]:
df1.head(2)

,verb_id,lex,scroll,book,chapter,verse_num,gcons_verb,gcons_verse,sign_info,stem,...,cmpl_indiv,cmpl_complex,motion_type,preposition_1,preposition_2,preposition_3,preposition_4,comments,reconstructed_verse,spatial_arg_type
0,28771_mt,BW>[,MT,Exodus,1,1,B>JM,W >LH CMWT BNJ JFR>L H B>JM MYRJMH >T J<QB >JC...,,qal,...,nmpr,simple,factive,,,,,,,goal
1,28778_mt,BW>[,MT,Exodus,1,1,B>W,W >LH CMWT BNJ JFR>L H B>JM MYRJMH >T J<QB >JC...,,qal,...,,,,,,,,,,

In [58]:
#df2

In [51]:
frames = [df1, df2]

In [52]:
df = pd.concat(frames).fillna("")

In [53]:
df.sort_values(["book", "chapter", "verse_num"], ascending=[True, True, True], ignore_index=True, inplace=True)

In [54]:
df = df.reset_index()

In [60]:
df.head(7)

,level_0,verb_id,lex,scroll,book,chapter,verse_num,gcons_verb,gcons_verse,sign_info,...,cmpl_complex,motion_type,preposition_1,preposition_2,preposition_3,preposition_4,comments,reconstructed_verse,spatial_arg_type,index
0,0,28771_mt,BW>[,MT,Exodus,1,1,B>JM,W >LH CMWT BNJ JFR>L H B>JM MYRJMH >T J<QB >JC...,,...,simple,factive,,,,,,,goal,
1,1,28778_mt,BW>[,MT,Exodus,1,1,B>W,W >LH CMWT BNJ JFR>L H B>JM MYRJMH >T J<QB >JC...,,...,,,,,,,,,,
2,2,28771_lxx,εἰσπορεύω,LXX,Exodus,1,1,εἰσπεπορευμένων,ταῦτα τὰ ὀνόματα τῶν υἱῶν Ἰσραὴλ εἰσ...,,...,,,εἰς,,,,this is a rare verb!,,,
3,3,28778_lxx,εἰσέρχομαι,LXX,Exodus,1,1,εἰσήλθοσαν,ταῦτα τὰ ὀνόματα τῶν υἱῶν Ἰσραὴλ εἰσ...,,...,,,,,,,,,,
4,4,1941992_dss,BW>[,4Q11,Exodus,1,1,B>W,>LH CMWT BNJ JFR>L H B>JM MYRJMH >T J<QB >JC W...,000 0000 000 00111 1 1111 111000 11 1111 111 0...,...,,,,,,,,>LH CMWT BNJ JF[R>L H B>JM MYR]JMH [>T J<QB >J...,,1.0
5,5,29061_mt,BW>[,MT,Exodus,1,19,TBW>,W T>MRN H MJLDT >L PR<H KJ L> K NCJM H MYRJT H...,,...,simple,factive,>L,,,,,,goal,
6,6,29061_lxx,εἰσέρχομαι,LXX,Exodus,1,19,εἰσελθεῖν,εἶπαν δὲ αἱ μαῖαι τῷ Φαραώ · οὐχ ὡς ...,,...,,,πρός,,,,,,,

In [61]:
df.to_csv("data/lxx_project_dataset.csv", index=False)